spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/account_posting_dev
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  level:
    com.accountposting: DEBUG
    org.hibernate.SQL: DEBUG
