spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

app:
  kafka:
    enabled: false
    topic:
      posting-success: account-posting-success

server:
  servlet:
    context-path: /api

logging:
  level:
    root: WARN
    com.accountposting: INFO
